# Generated by Django 5.0.7 on 2025-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    (1, "Bó Hoa"),
                    (2, "Giỏ Hoa"),
                    (3, "Hoa Đám Cưới"),
                    (4, "Hoa Khai Trương"),
                    (5, "Hoa Sinh Nhật"),
                    (6, "Hoa Tình Yêu"),
                    (7, "Hoa Baby"),
                    (8, "Cúc Mẫu Đơn"),
                    (9, "Chậu Lan Hồ Điệp"),
                    (10, "Hoa Tốt Ngiệp"),
                    (11, "Giỏ Trái Cây"),
                    (12, "Mâu Hoa Mới"),
                ],
                default=1,
                max_length=100,
            ),
        ),
    ]
