# Generated by Django 5.0.7 on 2025-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="title",
        ),
    ]
