# Generated by Django 5.0.7 on 2025-02-06 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_remove_product_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
