# Generated by Django 5.0.7 on 2025-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_product_category_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
