# Generated by Django 5.0.7 on 2025-04-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_product_image_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(default="DEFAULT123", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="abc", max_length=50, null=True),
        ),
    ]
