# Generated by Django 5.0.7 on 2025-04-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_product_product_code_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
