# Generated by Django 5.0.7 on 2025-04-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0022_cart_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_item",
            name="product",
            field=models.ForeignKey(
                default="Chưa có sản phẩm",
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
            ),
        ),
    ]
